### ISSUE TITLE
DB Year column missing

### ISSUE THREAD

**Issue by ppsantosmm** [vktrgama/quiniela#9]
I was trying to test your code, but seems to be incomplete in its database structure.

"System.Data.SqlClient.SqlException: Invalid column name 'Year'."

QuinielaService.cs Line: 740.

Do you have an update?

**Comment by vktrgama** [comment]
Hey Jose, sorry man, I coded this a long time ago (2018), and I have no updates, I probably added that column, later on, you can look at the DB schema scripts under the folder `App_Data`, if not saved there, I'm sure you can add it in your code.

**Comment by ppsantosmm** [comment]
> Hey Jose, sorry man, I coded this a long time ago (2018), and I have no updates, I probably added that column, later on, you can look at the DB schema scripts under the folder `App_Data`, if not saved there, I'm sure you can add it in your code.

Thanks @vktrgama, yesterday that column was added, now is working. Have a nice day.
